### ISSUE TITLE
[1.181011.0] On tab 'Snapshot' Update

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#1] opened 2018-10-12 23:07 UTC
### Steps to reproduce
Snapshot option only works on link in cell A2

### Expected Result
Suggest to have link auto update depending on selection in cell A5

### Actual Result
No matter what value is in cell A5, it updates based off of A2 link

### Version
1.181011.0

### Testcase
Provide a link to a copy of the TB Sheets if necessary

**Comment by DarkPhoenixSniper** [comment] 2018-10-12 23:14
Cell A2, should be the following formula to accommodate this check
=CONCATENATE("https://swgoh.gg/",VLOOKUP(A5,Roster!B:C,2))

**Comment by PopGoesTheWza** [comment] 2018-10-12 23:15
The function "get_player_link_" i where the problem is. When looking for a member, it assumes column C on Roster tab will hold the SwgohGg url for that member.

**Comment by DarkPhoenixSniper** [comment] 2018-10-12 23:17
except Column C on Roster tab is just /u/ALLYCODE   not full URL

**Comment by PopGoesTheWza** [comment] 2018-10-12 23:36
it would make sense to only have the allycode in column C.
I see a two step change:
First fixing get_player_link_() to recreate the url (Swgoh.Gg)
Second, generalize allycode in column C

**Comment by CyberShark98** [comment] 2018-10-14 23:05
How will you accommodate this for .help support? or is that already built in?

**Comment by CyberShark98** [comment] 2018-10-14 23:15
budsta95Today at 6:06 PM
so the error i saw was regarding the get_playerlink function in Code.gs
specifically the line var match = members.find(function (e) { return e[0] === memberName_1; });
when calling function() on the array, the exception thrown is "TypeError: Cannot find function find in object <contents of array>"
so instead of calling members.find() I just did a for loop where i checked for a match with memberName_1 and set playerLink if it is found
and the other part of the problem is in function playerSnapshot()
Line: var url = playerLink + "characters/?" + tag + "page=" + page;

Needs to be: var url = "https://swgoh.gg/" + playerLink + "characters/?" + tag + "page=" + page;
doing those two things makes snapshot work

**Comment by PopGoesTheWza** [comment] 2018-10-14 23:28
@DarkPhoenixSniper 
I need to think it over.
- Roster column C should only hold the allycode
- Current snapshot relies on parsing SwgohGg html page but now API is available for both SwgohGg and SwgohHelp
- When "snapshoting" a guild member, the Heroes tab already holds the members' data so it should use the data from the sheet rather than reading an external source.

What do you think?

**Comment by CyberShark98** [comment] 2018-10-14 23:30
I think it makes sense to make as few calls to external data sources as possible, especially since it could be down or could be busy. that way the only data being pulled is the data at the time of refresh?

**Comment by DarkPhoenixSniper** [comment] 2018-10-14 23:40
I agree with calling the information from the Heroes/Ship tabs, instead of pulling from the site.

**Comment by PopGoesTheWza** [comment] 2018-10-14 23:41
I will look into it sometime this week.

**Comment by PopGoesTheWza** [comment] 2018-10-15 15:45
@DarkPhoenixSniper @CyberShark98 
Fix is in testing and should be ready for next release.

**Closed** 2018-10-15 23:37 UTC
Labels: bug
