### ISSUE TITLE
[Bug? 1.181016.0] Add/Remove does not affect Discord List?

### ISSUE THREAD

**Issue by CyberShark98** [PopGoesTheWza/swgoh-tb-sheets#11] opened 2018-10-16 15:42 UTC
### Steps to reproduce
@Axe#4037  used Add/Remove, did a TB refresh, and did not see any change in the Discord list

**Comment by PopGoesTheWza** [comment] 2018-10-16 20:19
This is WAD (Work As Designed)

There is no limit (or at least there shouldn’t) to the number of Discord entries.
This Discord directory does not need to reflect the actual guild roster. This useful to guild alliances with many members going from one guild to another. You maintain a single list of members and their Discord ids which you copy and paste in each guild copy of the TB Sheets.

Does this answer your issue?

**Comment by DarkPhoenixSniper** [comment] 2018-10-16 23:49
@popgoesthewza maybe add those values on the Exception list? Idk

**Comment by PopGoesTheWza** [comment] 2018-10-17 10:12
@DarkPhoenixSniper I am not getting it.
Can you elaborate?

**Comment by DarkPhoenixSniper** [comment] 2018-10-17 11:15
I know the add/remove will be on the Roster sheet. Maybe add the Discord info to the Exclusions spreadsheet? The one with Light/Dark/Exclusions tabs that the main sheet imports?

**Comment by PopGoesTheWza** [comment] 2018-10-21 13:28
The Discord name/mentionId list is independant from the actual guild roster by design. I still cannot get the point about this issue.

**Comment by T-Co** [comment] 2018-10-27 13:35
My thought was that if a roster player, “Axe Grinder” already had already been selected and a discord id associated with that player, it would no longer appear as a possible selection. I wouldn’t think any player would need multiple discord IDs. So as the list of discord ids gets longer, there is no need to reconcile what players have been used/they are no longer available as an option.

**Comment by PopGoesTheWza** [comment] 2018-10-27 13:43
@T-Co interesting.
A pain to implement on first thought.
There are still occurences of a member of the guild having several accounts...
I need to consider how to implement and possible drawback it could have.

**Comment by PopGoesTheWza** [comment] 2018-10-30 13:31
@T-Co @DarkPhoenixSniper Requesting feedback:
I can implement that functionality, but it obviously has a side effect. Once a value is selected from the dropdown list, it is filtered out of the data validation rule... and thus you get the invalid indicator.
One could say it is merely cosmetic but is also likely to cause confusion among users.
![image](https://user-images.githubusercontent.com/32041843/47720989-72b82d00-dc4f-11e8-9475-9d6277953122.png)

**Comment by T-Co** [comment] 2018-10-31 02:38
Yeah, I see what you mean.  I don't think it's confusing because I know what's going on.  But someone unfamiliar probably would be confused.  Might be worth adding some sort of "note."  Otherwise, it may get posted in #ss_help_support regularly.  Otherwise, I like it!  Thanks for considering and implementing that!

**Comment by PopGoesTheWza** [comment] 2018-11-01 13:45
@skiadas now that you mention it… i’d Go for a simple conditional formatting where entries on the discord tab that match with Roster would have a light green background.

**Comment by PopGoesTheWza** [comment] 2018-11-02 21:04
This enhancement will be in next release.

**Comment by PopGoesTheWza** [comment] 2018-11-04 23:13
in next release

**Closed by PopGoesTheWza** 2018-11-04 23:13 UTC
Labels: enhancement
